id: I59DBB827
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:28:54+00:00'
last_modified: '2022-06-09T05:14:19.595725+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC442
  title: 'བུ་ལོན་སྐོར་གྱི་རྩོད་གཞི། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D921:
      image_group_id: I2PD18871
      title: ''
      total_pages: 178
      order: 1
      base_file: D921.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
