id: P008206
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:07:59.065351
source_metadata:
  id: bdr:W1AC442
  title: 'བུ་ལོན་སྐོར་གྱི་རྩོད་གཞི། '
  author: ''
  volumes:
    cb94cb350fc44f4d81dd2d4f18900b81:
      image_group_id: I2PD18871
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
